version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-edgar
    restart: unless-stopped
    ports:
      - 7474:7474 # HTTP Browser
      - 7687:7687 # Bolt
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH:-neo4j/password}
      - NEO4J_dbms_default__advertised__address=0.0.0.0
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - ./neo4jdata:/var/lib/neo4j/data
      - ./data/sample:/data/sample:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

# Notes:
# - This compose file mounts a local `neo4jdata` directory for the database files and the repository `data/sample`
#   (read-only) so you can restore the included `neo4j.dump`.
# - The default auth is `neo4j/password`. Override by setting the environment variable `NEO4J_AUTH` before
#   running `docker compose up` (PowerShell example shown in the README).
